### PR TITLE
add arm64 support to the install script

### PR DESCRIPTION
**Pull request by jbpratt**
also fail fast if running on unsupported arch

```
ubuntu@kitkat:~$ curl -sfL https://raw.githubusercontent.com/jbpratt/microshift/install-support-arm64/install.sh --output arm64-install.sh
ubuntu@kitkat:~$ vim arm64-install.sh
ubuntu@kitkat:~$ chmod +x arm64-install.sh
ubuntu@kitkat:~$ ./arm64-install.sh
======================================================================
!!! WARNING !!!
The hostname kitkat does not follow FQDN, which might cause problems while operating the cluster.
See: https://github.com/redhat-et/microshift/issues/176

If you face a problem or want to avoid them, please update your hostname and try again.
Example: 'sudo hostnamectl set-hostname kitkat.example.com'
======================================================================
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
conntrack is already the newest version (1:1.4.6-2).
firewalld is already the newest version (0.9.3-2ubuntu1).
policycoreutils-python-utils is already the newest version (3.1-1build1).
0 upgraded, 0 newly installed, 0 to remove and 106 not upgraded.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
100   393  100   393    0     0    395      0 --:--:-- --:--:-- --:--:--   395
100   394  100   394    0     0    355      0  0:00:01  0:00:01 --:--:--   355
100   395  100   395    0     0    323      0  0:00:01  0:00:01 --:--:--   323
100   396  100   396    0     0    296      0  0:00:01  0:00:01 --:--:--   296
100   397  100   397    0     0    273      0  0:00:01  0:00:01 --:--:--   273
100  1093  100  1093    0     0    696      0  0:00:01  0:00:01 --:--:--   696
OK
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
100  1093  100  1093    0     0   2824      0 --:--:-- --:--:-- --:--:--  2824
OK
Hit:1 http://ports.ubuntu.com/ubuntu-ports hirsute InRelease
Hit:2 http://ports.ubuntu.com/ubuntu-ports hirsute-updates InRelease
Hit:3 http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.20/xUbuntu_20.04  InRelease
Hit:4 http://ports.ubuntu.com/ubuntu-ports hirsute-backports InRelease
Hit:5 http://ports.ubuntu.com/ubuntu-ports hirsute-security InRelease
Hit:6 https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04  InRelease
Reading package lists... Done
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
containernetworking-plugins is already the newest version (100:1.0.0-1).
cri-o-runc is already the newest version (1.0.1~0).
cri-tools is already the newest version (1.21.0~2).
cri-o is already the newest version (1.20.5~0).
0 upgraded, 0 newly installed, 0 to remove and 106 not upgraded.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 41.4M  100 41.4M    0     0  14.7M      0  0:00:02  0:00:02 --:--:-- 14.7M
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   630  100   630    0     0   2930      0 --:--:-- --:--:-- --:--:--  2930
100  110M  100  110M    0     0  16.2M      0  0:00:06  0:00:06 --:--:-- 18.2M
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   622  100   622    0     0   3222      0 --:--:-- --:--:-- --:--:--  3206
100   178  100   178    0     0    529      0 --:--:-- --:--:-- --:--:--   529
[Unit]
Description=Microshift
After=crio.service

[Service]
WorkingDirectory=/usr/local/bin/
ExecStart=microshift run
Restart=always
User=root

[Install]
WantedBy=multi-user.target
Created symlink /etc/systemd/system/multi-user.target.wants/microshift.service → /lib/systemd/system/microshift.service.
ubuntu@kitkat:~$ microshift --help
Microshift, a minimal OpenShift

Usage:
  microshift [flags]
  microshift [command]

Available Commands:
  help        Help about any command
  run         Run Microshift
  version     Print Microshift version information

Flags:
      --alsologtostderr      log to standard error as well as files
  -h, --help                 help for microshift
      --log-dir string       If non-empty, write log files in this directory
  -v, --v Level              number for the log level verbosity
      --vmodule moduleSpec   comma-separated list of pattern=N settings for file-filtered logging

Use "microshift [command] --help" for more information about a command.
ubuntu@kitkat:~$ sudo systemctl status microshift.service
● microshift.service - Microshift
     Loaded: loaded (/lib/systemd/system/microshift.service; enabled; vendor preset: enabled)
     Active: active (running) since Sat 2021-09-18 02:26:32 UTC; 26s ago
   Main PID: 9304 (microshift)
      Tasks: 10 (limit: 9253)
     Memory: 284.6M
     CGroup: /system.slice/microshift.service
             └─9304 microshift run

Sep 18 02:26:51 kitkat microshift[9304]: W0918 02:26:51.816440    9304 genericapiserver.go:455] Skipping API discovery.k8s.io/v1alpha1 because it >
Sep 18 02:26:51 kitkat microshift[9304]: W0918 02:26:51.859043    9304 genericapiserver.go:455] Skipping API node.k8s.io/v1alpha1 because it has n>
Sep 18 02:26:51 kitkat microshift[9304]: W0918 02:26:51.889065    9304 genericapiserver.go:455] Skipping API rbac.authorization.k8s.io/v1alpha1 be>
Sep 18 02:26:51 kitkat microshift[9304]: W0918 02:26:51.902362    9304 genericapiserver.go:455] Skipping API scheduling.k8s.io/v1alpha1 because it>
Sep 18 02:26:51 kitkat microshift[9304]: W0918 02:26:51.926412    9304 genericapiserver.go:455] Skipping API storage.k8s.io/v1alpha1 because it ha>
Sep 18 02:26:51 kitkat microshift[9304]: W0918 02:26:51.937421    9304 genericapiserver.go:455] Skipping API flowcontrol.apiserver.k8s.io/v1alpha1>
Sep 18 02:26:51 kitkat microshift[9304]: W0918 02:26:51.958324    9304 genericapiserver.go:455] Skipping API apps/v1beta2 because it has no resour>
Sep 18 02:26:51 kitkat microshift[9304]: W0918 02:26:51.958434    9304 genericapiserver.go:455] Skipping API apps/v1beta1 because it has no resour>
Sep 18 02:26:51 kitkat microshift[9304]: I0918 02:26:51.992988    9304 plugins.go:158] Loaded 12 mutating admission controller(s) successfully in >
Sep 18 02:26:51 kitkat microshift[9304]: I0918 02:26:51.993109    9304 plugins.go:161] Loaded 10 validating admission controller(s) successfully i>
```

note: I can't run the entire script due to firewall issues in #285 so that gets disabled.

### CODE REVIEW

**Comment by jbpratt** [comment]
everything came up except the router, I don't think this issue is related.
```
ubuntu@kitkat:~$ kubectl logs pod/router-default-79f7dc4c6b-fb5tk -n openshift-ingress
I0918 02:37:54.696454       1 template.go:298] router "msg"="starting router"  "version"="majorFromGit: \nminorFromGit: \ncommitFromGit: c4901655\nversionFromGit: v0.0.0-unknown\ngitTreeState: clean\nbuildDate: 2021-08-23T13:46:41Z\n"
I0918 02:37:54.701065       1 metrics.go:154] metrics "msg"="router health and metrics port listening on HTTP and HTTPS"  "address"="0.0.0.0:1936"
I0918 02:37:54.709137       1 reflector.go:175] Starting reflector *v1.Service (30m0s) from github.com/openshift/router/pkg/router/template/service_lookup.go:33
I0918 02:37:54.719038       1 router.go:164] template "msg"="creating a new template router"  "writeDir"="/var/lib/haproxy"
I0918 02:37:54.719386       1 router.go:239] template "msg"="router will coalesce reloads within an interval of each other"  "interval"="5s"
I0918 02:37:54.721309       1 router.go:301] template "msg"="watching for changes"  "path"="/etc/pki/tls/private"
I0918 02:37:54.721679       1 router.go:257] router "msg"="router is including routes in all namespaces"
I0918 02:37:54.724542       1 reflector.go:175] Starting reflector *v1.Endpoints (30m0s) from github.com/openshift/router/pkg/router/controller/factory/factory.go:116
I0918 02:37:54.729767       1 reflector.go:175] Starting reflector *v1.Route (30m0s) from github.com/openshift/router/pkg/router/controller/factory/factory.go:116
I0918 02:38:26.548818       1 trace.go:116] Trace[609929405]: "Reflector ListAndWatch" name:github.com/openshift/router/pkg/router/template/service_lookup.go:33 (started: 2021-09-18 02:37:54.70955877 +0000 UTC m=+0.132525308) (total time: 31.8391634s):
Trace[609929405]: [31.839060661s] [31.839060661s] Objects listed
I0918 02:38:26.551966       1 trace.go:116] Trace[1374800177]: "Reflector ListAndWatch" name:github.com/openshift/router/pkg/router/controller/factory/factory.go:116 (started: 2021-09-18 02:37:54.724913143 +0000 UTC m=+0.147879644) (total time: 31.82697616s):
Trace[1374800177]: [31.826838884s] [31.826838884s] Objects listed
I0918 02:38:26.552851       1 trace.go:116] Trace[889162283]: "Reflector ListAndWatch" name:github.com/openshift/router/pkg/router/controller/factory/factory.go:116 (started: 2021-09-18 02:37:54.730063903 +0000 UTC m=+0.153030404) (total time: 31.822714742s):
Trace[889162283]: [31.822662428s] [31.822662428s] Objects listed
E0918 02:38:26.633029       1 haproxy.go:418] can't scrape HAProxy: dial unix /var/lib/haproxy/run/haproxy.sock: connect: no such file or directory
I0918 02:38:26.746664       1 router.go:540] template "msg"="router reloaded"  "output"="[WARNING] 260/023826 (18) : parsing [/var/lib/haproxy/conf/haproxy.config:54]: option 'http-use-htx' is deprecated and ignored. The HTX mode is now the only supported mode.\n - Checking http://localhost:80 ...\n - Health check ok : 0 retry attempt(s).\n"
I0918 02:38:31.747304       1 router.go:540] template "msg"="router reloaded"  "output"="[WARNING] 260/023831 (29) : parsing [/var/lib/haproxy/conf/haproxy.config:54]: option 'http-use-htx' is deprecated and ignored. The HTX mode is now the only supported mode.\n - Checking http://localhost:80 ...\n - Health check ok : 0 retry attempt(s).\n"
ubuntu@kitkat:~$ kubectl get pods -A
NAMESPACE                       NAME                                  READY   STATUS             RESTARTS   AGE
kube-system                     kube-flannel-ds-h4mm6                 1/1     Running            0          12m
kubevirt-hostpath-provisioner   kubevirt-hostpath-provisioner-rgcpf   1/1     Running            0          12m
openshift-dns                   dns-default-ksbdr                     3/3     Running            0          12m
openshift-ingress               router-default-79f7dc4c6b-fb5tk       0/1     CrashLoopBackOff   6          12m
openshift-service-ca            service-ca-58798776fb-pzh7p           1/1     Running            0          12m
```

**Comment by jbpratt** [comment]
Restarting seems to work sometimes but there are a lot of errors once it has started. Not sure if this is expected.

```
ubuntu@kitkat:~$ kubectl logs pod/router-default-79f7dc4c6b-fb5tk -n openshift-ingress
I0918 03:05:53.917372       1 template.go:298] router "msg"="starting router"  "version"="majorFromGit: \nminorFromGit: \ncommitFromGit: c4901655\nversionFromGit: v0.0.0-unknown\ngitTreeState: clean\nbuildDate: 2021-08-23T13:46:41Z\n"
I0918 03:05:53.924519       1 metrics.go:154] metrics "msg"="router health and metrics port listening on HTTP and HTTPS"  "address"="0.0.0.0:1936"
I0918 03:05:53.931745       1 reflector.go:175] Starting reflector *v1.Service (30m0s) from github.com/openshift/router/pkg/router/template/service_lookup.go:33
I0918 03:05:53.944258       1 router.go:164] template "msg"="creating a new template router"  "writeDir"="/var/lib/haproxy"
I0918 03:05:53.944528       1 router.go:239] template "msg"="router will coalesce reloads within an interval of each other"  "interval"="5s"
I0918 03:05:53.946571       1 router.go:301] template "msg"="watching for changes"  "path"="/etc/pki/tls/private"
I0918 03:05:53.946882       1 router.go:257] router "msg"="router is including routes in all namespaces"
I0918 03:05:53.947702       1 reflector.go:175] Starting reflector *v1.Route (30m0s) from github.com/openshift/router/pkg/router/controller/factory/factory.go:116
I0918 03:05:53.949153       1 reflector.go:175] Starting reflector *v1.Endpoints (30m0s) from github.com/openshift/router/pkg/router/controller/factory/factory.go:116
E0918 03:05:54.060038       1 haproxy.go:418] can't scrape HAProxy: dial unix /var/lib/haproxy/run/haproxy.sock: connect: no such file or directory
I0918 03:05:54.174592       1 router.go:540] template "msg"="router reloaded"  "output"="[WARNING] 260/030554 (19) : parsing [/var/lib/haproxy/conf/haproxy.config:54]: option 'http-use-htx' is deprecated and ignored. The HTX mode is now the only supported mode.\n - Checking http://localhost:80 ...\n - Health check ok : 0 retry attempt(s).\n"
E0918 12:20:26.453969       1 reflector.go:382] github.com/openshift/router/pkg/router/controller/factory/factory.go:116: Failed to watch *v1.Route: Get "https://10.43.0.1:443/apis/route.openshift.io/v1/routes?allowWatchBookmarks=true&resourceVersion=1939&timeout=8m25s&timeoutSeconds=505&watch=true": dial tcp 10.43.0.1:443: connect: connection refused
E0918 12:20:26.454257       1 reflector.go:382] github.com/openshift/router/pkg/router/template/service_lookup.go:33: Failed to watch *v1.Service: Get "https://10.43.0.1:443/api/v1/services?allowWatchBookmarks=true&resourceVersion=1832&timeout=8m41s&timeoutSeconds=521&watch=true": dial tcp 10.43.0.1:443: connect: connection refused
E0918 12:20:26.460092       1 reflector.go:382] github.com/openshift/router/pkg/router/controller/factory/factory.go:116: Failed to watch *v1.Endpoints: Get "https://10.43.0.1:443/api/v1/endpoints?allowWatchBookmarks=true&resourceVersion=1975&timeout=8m39s&timeoutSeconds=519&watch=true": dial tcp 10.43.0.1:443: connect: connection refused
E0918 12:20:27.459649       1 reflector.go:382] github.com/openshift/router/pkg/router/controller/factory/factory.go:116: Failed to watch *v1.Route: Get "https://10.43.0.1:443/apis/route.openshift.io/v1/routes?allowWatchBookmarks=true&resourceVersion=1939&timeout=8m7s&timeoutSeconds=487&watch=true": dial tcp 10.43.0.1:443: connect: network is unreachable
E0918 12:20:27.460874       1 reflector.go:382] github.com/openshift/router/pkg/router/template/service_lookup.go:33: Failed to watch *v1.Service: Get "https://10.43.0.1:443/api/v1/services?allowWatchBookmarks=true&resourceVersion=1832&timeout=6m51s&timeoutSeconds=411&watch=true": dial tcp 10.43.0.1:443: connect: network is unreachable
I0918 12:25:04.871401       1 template.go:298] router "msg"="starting router"  "version"="majorFromGit: \nminorFromGit: \ncommitFromGit: c4901655\nversionFromGit: v0.0.0-unknown\ngitTreeState: clean\nbuildDate: 2021-08-23T13:46:41Z\n"
I0918 12:25:04.877041       1 metrics.go:154] metrics "msg"="router health and metrics port listening on HTTP and HTTPS"  "address"="0.0.0.0:1936"
I0918 12:25:04.883765       1 reflector.go:175] Starting reflector *v1.Service (30m0s) from github.com/openshift/router/pkg/router/template/service_lookup.go:33
I0918 12:25:04.899484       1 router.go:164] template "msg"="creating a new template router"  "writeDir"="/var/lib/haproxy"
I0918 12:25:04.899774       1 router.go:239] template "msg"="router will coalesce reloads within an interval of each other"  "interval"="5s"
I0918 12:25:04.901578       1 router.go:301] template "msg"="watching for changes"  "path"="/etc/pki/tls/private"
I0918 12:25:04.901995       1 router.go:257] router "msg"="router is including routes in all namespaces"
I0918 12:25:04.903170       1 reflector.go:175] Starting reflector *v1.Route (30m0s) from github.com/openshift/router/pkg/router/controller/factory/factory.go:116
I0918 12:25:04.903198       1 reflector.go:175] Starting reflector *v1.Endpoints (30m0s) from github.com/openshift/router/pkg/router/controller/factory/factory.go:116
E0918 12:25:05.021926       1 haproxy.go:418] can't scrape HAProxy: dial unix /var/lib/haproxy/run/haproxy.sock: connect: no such file or directory
I0918 12:25:05.624717       1 router.go:540] template "msg"="router reloaded"  "output"="[WARNING] 260/122505 (20) : parsing [/var/lib/haproxy/conf/haproxy.config:54]: option 'http-use-htx' is deprecated and ignored. The HTX mode is now the only supported mode.\n - Checking http://localhost:80 ...\n - Health check ok : 0 retry attempt(s).\n"
ubuntu@kitkat:~$ sudo systemctl restart microshift.service
ubuntu@kitkat:~$ sudo systemctl status microshift.service
● microshift.service - Microshift
     Loaded: loaded (/lib/systemd/system/microshift.service; enabled; vendor preset: enabled)
     Active: active (running) since Sat 2021-09-18 12:28:12 UTC; 27s ago
   Main PID: 4347 (microshift)
      Tasks: 17 (limit: 9253)
     Memory: 442.8M
     CGroup: /system.slice/microshift.service
             └─4347 microshift run

Sep 18 12:28:39 kitkat microshift[4347]: I0918 12:28:39.909732    4347 controllermanager.go:590] Started "clusterrole-aggregation"
Sep 18 12:28:39 kitkat microshift[4347]: I0918 12:28:39.910042    4347 clusterroleaggregation_controller.go:149] Starting ClusterRoleAggregator
Sep 18 12:28:39 kitkat microshift[4347]: I0918 12:28:39.910081    4347 shared_informer.go:240] Waiting for caches to sync for ClusterRoleAggregator
Sep 18 12:28:40 kitkat microshift[4347]: I0918 12:28:40.059405    4347 controllermanager.go:590] Started "persistentvolume-expander"
Sep 18 12:28:40 kitkat microshift[4347]: I0918 12:28:40.059603    4347 expand_controller.go:310] Starting expand controller
Sep 18 12:28:40 kitkat microshift[4347]: I0918 12:28:40.059650    4347 shared_informer.go:240] Waiting for caches to sync for expand
Sep 18 12:28:40 kitkat microshift[4347]: W0918 12:28:40.179503    4347 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is de>
Sep 18 12:28:40 kitkat microshift[4347]: time="2021-09-18T12:28:40Z" level=info msg="waiting openshift CRD assets/crd/0000_11_imageregistry-config>
Sep 18 12:28:40 kitkat microshift[4347]: W0918 12:28:40.216977    4347 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is de>
Sep 18 12:28:40 kitkat microshift[4347]: time="2021-09-18T12:28:40Z" level=info msg="applying openshift CRD assets/crd/0000_03_authorization-opens>
 ESCOCdor preset: enabled)

ntrollermanager.go:590] Started "clusterrole-aggregation"
usterroleaggregation_controller.go:149] Starting ClusterRoleAggregator
ared_informer.go:240] Waiting for caches to sync for ClusterRoleAggregator
ntrollermanager.go:590] Started "persistentvolume-expander"
pand_controller.go:310] Starting expand controller
ared_informer.go:240] Waiting for caches to sync for expand
rnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 Cu>
l=info msg="waiting openshift CRD assets/crd/0000_11_imageregistry-configs.crd.yaml"
rnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 Cu>
l=info msg="applying openshift CRD assets/crd/0000_03_authorization-openshift_01_rolebindingrestriction.crd.yaml"
ubuntu@kitkat:~$ kubectl get pods -A
NAMESPACE                       NAME                                  READY   STATUS    RESTARTS   AGE
kube-system                     kube-flannel-ds-h4mm6                 1/1     Running   0          10h
kubevirt-hostpath-provisioner   kubevirt-hostpath-provisioner-rgcpf   1/1     Running   0          10h
openshift-dns                   dns-default-ksbdr                     3/3     Running   0          10h
openshift-ingress               router-default-79f7dc4c6b-fb5tk       1/1     Running   1          10h
openshift-service-ca            service-ca-58798776fb-pzh7p           1/1     Running   0          10h
ubuntu@kitkat:~$ kubectl logs pod/router-default-79f7dc4c6b-fb5tk -n openshift-ingress
I0918 03:05:53.917372       1 template.go:298] router "msg"="starting router"  "version"="majorFromGit: \nminorFromGit: \ncommitFromGit: c4901655\nversionFromGit: v0.0.0-unknown\ngitTreeState: clean\nbuildDate: 2021-08-23T13:46:41Z\n"
I0918 03:05:53.924519       1 metrics.go:154] metrics "msg"="router health and metrics port listening on HTTP and HTTPS"  "address"="0.0.0.0:1936"
I0918 03:05:53.931745       1 reflector.go:175] Starting reflector *v1.Service (30m0s) from github.com/openshift/router/pkg/router/template/service_lookup.go:33
I0918 03:05:53.944258       1 router.go:164] template "msg"="creating a new template router"  "writeDir"="/var/lib/haproxy"
I0918 03:05:53.944528       1 router.go:239] template "msg"="router will coalesce reloads within an interval of each other"  "interval"="5s"
I0918 03:05:53.946571       1 router.go:301] template "msg"="watching for changes"  "path"="/etc/pki/tls/private"
I0918 03:05:53.946882       1 router.go:257] router "msg"="router is including routes in all namespaces"
I0918 03:05:53.947702       1 reflector.go:175] Starting reflector *v1.Route (30m0s) from github.com/openshift/router/pkg/router/controller/factory/factory.go:116
I0918 03:05:53.949153       1 reflector.go:175] Starting reflector *v1.Endpoints (30m0s) from github.com/openshift/router/pkg/router/controller/factory/factory.go:116
E0918 03:05:54.060038       1 haproxy.go:418] can't scrape HAProxy: dial unix /var/lib/haproxy/run/haproxy.sock: connect: no such file or directory
I0918 03:05:54.174592       1 router.go:540] template "msg"="router reloaded"  "output"="[WARNING] 260/030554 (19) : parsing [/var/lib/haproxy/conf/haproxy.config:54]: option 'http-use-htx' is deprecated and ignored. The HTX mode is now the only supported mode.\n - Checking http://localhost:80 ...\n - Health check ok : 0 retry attempt(s).\n"
E0918 12:20:26.453969       1 reflector.go:382] github.com/openshift/router/pkg/router/controller/factory/factory.go:116: Failed to watch *v1.Route: Get "https://10.43.0.1:443/apis/route.openshift.io/v1/routes?allowWatchBookmarks=true&resourceVersion=1939&timeout=8m25s&timeoutSeconds=505&watch=true": dial tcp 10.43.0.1:443: connect: connection refused
E0918 12:20:26.454257       1 reflector.go:382] github.com/openshift/router/pkg/router/template/service_lookup.go:33: Failed to watch *v1.Service: Get "https://10.43.0.1:443/api/v1/services?allowWatchBookmarks=true&resourceVersion=1832&timeout=8m41s&timeoutSeconds=521&watch=true": dial tcp 10.43.0.1:443: connect: connection refused
E0918 12:20:26.460092       1 reflector.go:382] github.com/openshift/router/pkg/router/controller/factory/factory.go:116: Failed to watch *v1.Endpoints: Get "https://10.43.0.1:443/api/v1/endpoints?allowWatchBookmarks=true&resourceVersion=1975&timeout=8m39s&timeoutSeconds=519&watch=true": dial tcp 10.43.0.1:443: connect: connection refused
E0918 12:20:27.459649       1 reflector.go:382] github.com/openshift/router/pkg/router/controller/factory/factory.go:116: Failed to watch *v1.Route: Get "https://10.43.0.1:443/apis/route.openshift.io/v1/routes?allowWatchBookmarks=true&resourceVersion=1939&timeout=8m7s&timeoutSeconds=487&watch=true": dial tcp 10.43.0.1:443: connect: network is unreachable
E0918 12:20:27.460874       1 reflector.go:382] github.com/openshift/router/pkg/router/template/service_lookup.go:33: Failed to watch *v1.Service: Get "https://10.43.0.1:443/api/v1/services?allowWatchBookmarks=true&resourceVersion=1832&timeout=6m51s&timeoutSeconds=411&watch=true": dial tcp 10.43.0.1:443: connect: network is unreachable
I0918 12:25:04.871401       1 template.go:298] router "msg"="starting router"  "version"="majorFromGit: \nminorFromGit: \ncommitFromGit: c4901655\nversionFromGit: v0.0.0-unknown\ngitTreeState: clean\nbuildDate: 2021-08-23T13:46:41Z\n"
I0918 12:25:04.877041       1 metrics.go:154] metrics "msg"="router health and metrics port listening on HTTP and HTTPS"  "address"="0.0.0.0:1936"
I0918 12:25:04.883765       1 reflector.go:175] Starting reflector *v1.Service (30m0s) from github.com/openshift/router/pkg/router/template/service_lookup.go:33
I0918 12:25:04.899484       1 router.go:164] template "msg"="creating a new template router"  "writeDir"="/var/lib/haproxy"
I0918 12:25:04.899774       1 router.go:239] template "msg"="router will coalesce reloads within an interval of each other"  "interval"="5s"
I0918 12:25:04.901578       1 router.go:301] template "msg"="watching for changes"  "path"="/etc/pki/tls/private"
I0918 12:25:04.901995       1 router.go:257] router "msg"="router is including routes in all namespaces"
I0918 12:25:04.903170       1 reflector.go:175] Starting reflector *v1.Route (30m0s) from github.com/openshift/router/pkg/router/controller/factory/factory.go:116
I0918 12:25:04.903198       1 reflector.go:175] Starting reflector *v1.Endpoints (30m0s) from github.com/openshift/router/pkg/router/controller/factory/factory.go:116
E0918 12:25:05.021926       1 haproxy.go:418] can't scrape HAProxy: dial unix /var/lib/haproxy/run/haproxy.sock: connect: no such file or directory
I0918 12:25:05.624717       1 router.go:540] template "msg"="router reloaded"  "output"="[WARNING] 260/122505 (20) : parsing [/var/lib/haproxy/conf/haproxy.config:54]: option 'http-use-htx' is deprecated and ignored. The HTX mode is now the only supported mode.\n - Checking http://localhost:80 ...\n - Health check ok : 0 retry attempt(s).\n"
E0918 12:28:12.402215       1 reflector.go:382] github.com/openshift/router/pkg/router/controller/factory/factory.go:116: Failed to watch *v1.Endpoints: Get "https://10.43.0.1:443/api/v1/endpoints?allowWatchBookmarks=true&resourceVersion=13408&timeout=9m32s&timeoutSeconds=572&watch=true": dial tcp 10.43.0.1:443: connect: connection refused
E0918 12:28:12.402486       1 reflector.go:382] github.com/openshift/router/pkg/router/controller/factory/factory.go:116: Failed to watch *v1.Route: Get "https://10.43.0.1:443/apis/route.openshift.io/v1/routes?allowWatchBookmarks=true&resourceVersion=13372&timeout=5m46s&timeoutSeconds=346&watch=true": dial tcp 10.43.0.1:443: connect: connection refused
E0918 12:28:12.403421       1 reflector.go:382] github.com/openshift/router/pkg/router/template/service_lookup.go:33: Failed to watch *v1.Service: Get "https://10.43.0.1:443/api/v1/services?allowWatchBookmarks=true&resourceVersion=13327&timeout=8m55s&timeoutSeconds=535&watch=true": dial tcp 10.43.0.1:443: connect: connection refused
E0918 12:28:13.404619       1 reflector.go:382] github.com/openshift/router/pkg/router/controller/factory/factory.go:116: Failed to watch *v1.Endpoints: Get "https://10.43.0.1:443/api/v1/endpoints?allowWatchBookmarks=true&resourceVersion=13408&timeout=5m25s&timeoutSeconds=325&watch=true": dial tcp 10.43.0.1:443: connect: connection refused
E0918 12:28:13.407432       1 reflector.go:382] github.com/openshift/router/pkg/router/controller/factory/factory.go:116: Failed to watch *v1.Route: Get "https://10.43.0.1:443/apis/route.openshift.io/v1/routes?allowWatchBookmarks=true&resourceVersion=13372&timeout=6m1s&timeoutSeconds=361&watch=true": dial tcp 10.43.0.1:443: connect: connection refused
E0918 12:28:13.408913       1 reflector.go:382] github.com/openshift/router/pkg/router/template/service_lookup.go:33: Failed to watch *v1.Service: Get "https://10.43.0.1:443/api/v1/services?allowWatchBookmarks=true&resourceVersion=13327&timeout=7m46s&timeoutSeconds=466&watch=true": dial tcp 10.43.0.1:443: connect: connection refused
E0918 12:28:14.407488       1 reflector.go:382] github.com/openshift/router/pkg/router/controller/factory/factory.go:116: Failed to watch *v1.Endpoints: Get "https://10.43.0.1:443/api/v1/endpoints?allowWatchBookmarks=true&resourceVersion=13408&timeout=5m0s&timeoutSeconds=300&watch=true": dial tcp 10.43.0.1:443: connect: connection refused
E0918 12:28:14.409336       1 reflector.go:382] github.com/openshift/router/pkg/router/controller/factory/factory.go:116: Failed to watch *v1.Route: Get "https://10.43.0.1:443/apis/route.openshift.io/v1/routes?allowWatchBookmarks=true&resourceVersion=13372&timeout=9m9s&timeoutSeconds=549&watch=true": dial tcp 10.43.0.1:443: connect: connection refused
E0918 12:28:14.410589       1 reflector.go:382] github.com/openshift/router/pkg/router/template/service_lookup.go:33: Failed to watch *v1.Service: Get "https://10.43.0.1:443/api/v1/services?allowWatchBookmarks=true&resourceVersion=13327&timeout=7m10s&timeoutSeconds=430&watch=true": dial tcp 10.43.0.1:443: connect: connection refused
E0918 12:28:28.691157       1 reflector.go:382] github.com/openshift/router/pkg/router/controller/factory/factory.go:116: Failed to watch *v1.Route: the server is currently unable to handle the request (get routes.route.openshift.io)
E0918 12:28:29.701463       1 reflector.go:178] github.com/openshift/router/pkg/router/controller/factory/factory.go:116: Failed to list *v1.Route: the server is currently unable to handle the request (get routes.route.openshift.io)
E0918 12:28:32.826486       1 reflector.go:178] github.com/openshift/router/pkg/router/controller/factory/factory.go:116: Failed to list *v1.Route: the server is currently unable to handle the request (get routes.route.openshift.io)
E0918 12:28:37.965694       1 reflector.go:178] github.com/openshift/router/pkg/router/controller/factory/factory.go:116: Failed to list *v1.Route: the server is currently unable to handle the request (get routes.route.openshift.io)
E0918 12:28:47.096788       1 reflector.go:178] github.com/openshift/router/pkg/router/controller/factory/factory.go:116: Failed to list *v1.Route: the server is currently unable to handle the request (get routes.route.openshift.io)
E0918 12:29:02.745108       1 reflector.go:178] github.com/openshift/router/pkg/router/controller/factory/factory.go:116: Failed to list *v1.Route: the server is currently unable to handle the request (get routes.route.openshift.io)
E0918 12:29:28.644187       1 reflector.go:178] github.com/openshift/router/pkg/router/controller/factory/factory.go:116: Failed to list *v1.Route: the server is currently unable to handle the request (get routes.route.openshift.io)
```

**Comment by rootfs** [comment]
thank you for taking this! a couple of comments. @carlosedp has made microshift runnable on risc-v and ppc64le. He also built the container images on arm64.

**Pull request merged**
