### PR TITLE
initial commit of metal LB doc

### LINKED ISSUE #340: [Enhancement] Look at how to provide VIPs in local network
Analyze:

   * MetalLB
   *  https://kube-vip.io/?

### PR DESCRIPTION
**Pull request by cooktheryan**
Closes #340

### CODE REVIEW

**Comment by cooktheryan** [comment]
@iranzo is there anything I should do to ensure that this file will get picked up for the webpage?

**Comment by iranzo** [comment]
> @iranzo is there anything I should do to ensure that this file will get picked up for the webpage?

1- Put some content ;-) 
2- Put yaml preamble
3- probably... link it on the main menu if it's a 'page' in the same way as others are linked in the _config.yaml

**Review by mangelajo — CHANGES_REQUESTED** [review]
Hmm, something happened the commit looks empty

**Comment by cooktheryan** [comment]
well that is weird...

**Comment by iranzo** [comment]
Soooo, next step is probably adding yaml preamble, I would merge as it is now, so that the content is there, and move to different repo all the website stuff to make it easier to add content and preview witout getting everyone else nervous with the pr's :)

**Comment by cooktheryan** [comment]
moving to docs repo

**Pull request closed without merging**
