### PR TITLE
link fix

### LINKED ISSUE #444: [BUG] Broken links in main MicroShift README
The "Deployment models" section has two links that are broken:

- Install as a container via Podman, utilizing cri-o runtime and be lifecycle-managed by systemd 
- Run an all-in-one microshift deployment on which devs can test their applications locally.

### PR DESCRIPTION
**Pull request by cooktheryan**
**Which issue(s) this PR addresses**:
Closes #444

### CODE REVIEW

**Comment by sallyom** [comment]
Thanks!
/lgtm

**Review by husky-parul — APPROVED** [review]
/lgtm

**Review by husky-parul — APPROVED** [review]
/approved

**Pull request merged**
