### PR TITLE
Make kube-scheduler Service return errors for healthcheck

### PR DESCRIPTION
**Pull request by mangelajo**
Signed-off-by: Miguel Angel Ajo <majopela@redhat.com>

### CODE REVIEW

**Comment by fzdarsky** [comment]
See #585. Need to either panic on error here or globally.

**Comment by mangelajo** [comment]
> See #585. Need to either panic on error here or globally.

>> Just noticed that returning an error instead of panicing means the ServiceManager just logs the service as stopped (with error) but MicroShift continues running in an undefined state. Need to either panic on error here or globally.


Not after https://github.com/redhat-et/microshift/pull/575 , I think it's ok now to move back to LGTM :-)

**Pull request merged**
