### PR TITLE
Fix high CPU load issue

### PR DESCRIPTION
**Pull request by fzdarsky**
Signed-off-by: Frank A. Zdarsky <fzdarsky@redhat.com>

### CODE REVIEW

**Review by guymguym — COMMENTED** [review]
@fzdarsky The recursive imple of `And()` is a bit too delicate IMHO.
Wouldn't you prefer a more straightforward impl with sync.WaitGroup where every channel is waited in its own go routine?

**Comment by rootfs** [comment]
The high cpu issue resolved, let's take this patch. @guymguym improvement welcome

**Pull request merged**
