### PR TITLE
fix flannel

### PR DESCRIPTION
**Pull request by mangelajo**
Flannel wasn't completely installed, since the host needs the flannel
 binary in /opt/cni/bin for crio to find, and forceAddress is necessary
 to make sure that the cni0 bridge will have the address requested
 by flannel.
    
 An alternative to this could be creating a flannel-cni rpm sub-package
 to be installed on the host.

### CODE REVIEW

**Comment by rootfs** [comment]
CI is flaky at the moment, will retest later.

**Comment by oglok** [comment]
The cni plugin seems not to be statically compiled:

```
/opt/cni/bin/flannel: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by /opt/cni/bin/flannel)
```

**Comment by oglok** [comment]
It seems to be working now:
```
 18 13:58:34 fedora crio[645]: time="2021-11-18 13:58:34.826304102Z" level=info msg="About to add CNI network cbr0 (type=flannel)"
Nov 18 13:58:34 fedora crio[645]: map[string]interface {}{"cniVersion":"0.3.1", "forceAddress":true, "hairpinMode":true, "ipMasq":false, "ipam":map[string]interface {}{"ranges":[][]ma>
Nov 18 13:58:34 fedora crio[645]: {"cniVersion":"0.3.1","forceAddress":true,"hairpinMode":true,"ipMasq":false,"ipam":{"ranges":[[{"subnet":"10.42.0.0/24"}]],"routes":[{"dst":"10.42.0.>
Nov 18 13:58:34 fedora crio[645]: time="2021-11-18 13:58:34.963270340Z" level=info msg="About to check CNI network cbr0 (type=flannel)"
```

**Review by oglok — COMMENTED** [review]
/lgtm

**Pull request merged**
