### PR TITLE
Uninstall script

### PR DESCRIPTION
**Pull request by cooktheryan**
Carry-on from @tosin2013 #179 

Adding clean up script for issue 168
#168

### CODE REVIEW

**Comment by mangelajo** [comment]
Looks good, github says it needs a rebase.

Let's squash it at merge (or during the rebase process) thanks Ryan!

**Comment by cooktheryan** [comment]
@copejon can I get a review on this one

**Comment by cooktheryan** [comment]
closing as we are going to move to RPMs and containers soon

**Pull request closed without merging**
