### PR TITLE
Make kube-api-server to return errors from healthcheck

### PR DESCRIPTION
**Pull request by mangelajo**
Signed-off-by: Miguel Angel Ajo <majopela@redhat.com>

### CODE REVIEW

**Comment by fzdarsky** [comment]
Had to wrap my head around the various conditions on the error channel, but that makes much sense.

/lgtm

**Comment by fzdarsky** [comment]
Just noticed that returning an error instead of panicing means the ServiceManager just logs the service as stopped (with error) but MicroShift continues running in an undefined state. Need to either panic on error here or globabally.

**Comment by mangelajo** [comment]
> 

Not after https://github.com/redhat-et/microshift/pull/575 , I think it's ok now to move back to LGTM :-)

**Pull request merged**
