### PR TITLE
[WIP] Change kubeconfigs to point to the host IP

### PR DESCRIPTION
**Pull request by oglok**
Signed-off-by: Ricardo Noriega <rnoriega@redhat.com>

### CODE REVIEW

**Comment by oglok** [comment]
I'm now thinking about the case where the device is restarted and the IP address changes due to a dhcp renewal. MicroShift will keep the host IP in the kubeconfigs and it'll crash. 

Would that work with microshift.cluster.local using mDNS? @mangelajo

**Comment by cooktheryan** [comment]
what about using a name in the kubeconfigs? That way if the DHCP address changes the name should get patched as well. I think it would net us more possibilities for customers in the event that the facility in which microshift was running has some sort of VPN back to a home base a users could then load the kubeconfig into Argo and app of apps if they wanted

**Comment by mangelajo** [comment]
> I'm now thinking about the case where the device is restarted and the IP address changes due to a dhcp renewal. MicroShift will keep the host IP in the kubeconfigs and it'll crash.
> 
> Would that work with microshift.cluster.local using mDNS? @mangelajo

yes, mDNS would handle this, via microshift.local or hostname.local etc .. :)

**Comment by mangelajo** [comment]
included in https://github.com/redhat-et/microshift/pull/471

**Pull request closed without merging**
